package entity;
// Generated 09/06/2018 04:02:46 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Alumno generated by hbm2java
 */
@Entity
@Table(name="alumno"
    ,catalog="java_demo1"
)
public class Alumno  implements java.io.Serializable {


     private Integer id;
     private String nombres;
     private String apellidos;
     private Set<Curso> cursos = new HashSet<Curso>(0);

    public Alumno() {
    }

    public Alumno(String nombres, String apellidos, Set<Curso> cursos) {
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.cursos = cursos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="nombres", length=45)
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }

    
    @Column(name="apellidos", length=45)
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="alumno_has_curso", catalog="java_demo1", joinColumns = { 
        @JoinColumn(name="alumno_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="curso_id", nullable=false, updatable=false) })
    public Set<Curso> getCursos() {
        return this.cursos;
    }
    
    public void setCursos(Set<Curso> cursos) {
        this.cursos = cursos;
    }




}


